### ISSUE TITLE
Search doesn't provide feedback if results not found

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter.github.io#108]
## Steps to Reproduce ##

1. Go to the [docs page](https://domokit.github.io/docs/sky/index.html)
2. Type `yaml` into the search box
3. Hit return

## Actual Result ##

Nothing happens

## Expected Result ##

A search-results-page appears for `yaml`.  Since the docs search seems to be entirely powered by a precalculated index, perhaps an autocomplete suggestion that reads "There isn't a docs page for `yaml`," would suffice.

**Comment by sethladd** [comment]
Hm, Flutter has a dependency on YAML, but it doesn't itself provide the YAML library.

Dart doesn't have a good way to search all docs in the Dartiverse. You could visit dartdocs.org and search there, but it's not a nice "find as you type search". Alternatively, you could google for "dart yaml api".

Really appreciate the report, but not much we can do here in the Flutter docs themselves (because they are the API docs for Flutter itself). Going to close this, but happy to chat more in person to brainstorm ideas.

(in the meantime, if you want to suggest improvements to the dartdoc tool, check out https://github.com/dart-lang/dartdoc/issues)
