### ISSUE TITLE
A better way to explain how Counter "delegates" ?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter.github.io#41]
From http://flutter.io/tutorial/

"Notice how Counter now delegates responsibility for incrementing and displaying the counter value down to CounterIncrementor and CounterDisplay, respectively." 

Is _delegates_ the right word here? Looking at Counter, all it does is create _CounterState.

Maybe: "Notice how we created two new stateless components, cleaning separating the concerns of _displaying the counter_ (CounterDisplay) and _changing the counter_ (CounterIncrementor)."

Thoughts?

**Comment by krisgiesing** [comment]
I should have said "Counter's state delegates" instead of "Counter delegates" since it's the state doing the delegation. Also, what's being delegated is not the counter increment exactly, but gathering the user's decision to increment the counter.

"Delegates" might not be the best phrasing since it has a specific technical meaning in some contexts.  I was using it in a general sense here.

Your rephrasing is fine with me.

**Comment by sethladd** [comment]
Thanks for your comment. Will send up a PR.
